- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/45"
    job: "/usr/bin/ansible-pull -o -U https://github.com/spicyrice2077/ansible.git > /dev/null"
