- name: Gather package facts
  package_facts:
    manager: auto

- name: Install only available packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - cmatrix
    - ranger
    - nmap
    - htop
    - feroxbuster
    - autorecon
    - vscodium
    - rlwrap
  when: item not in ansible_facts.packages
  ignore_errors: yes
